# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
