# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
